version: '3.1'
services:
  warehouse-management:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=warehouse_management
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"